Even more ai updates
DamnedNForsaken/MMLX pull request #227
Opened 2021-11-30 21:56 UTC by DamnedNForsaken

Hotfixes for:
Bomb,
180 turn,
Making the HUD UI look alittle better (smaller and cleaner)

2021-12-02 09:08 UTC, JJChalupnik requested changes
Ok... Got to spend some good time with this build. Here are my observations/notes/fix requests. Some are things I'd like to add to our Issues, but some are big bugs that need squashing. Here it goes:

- Hanging Auto Hand Switch and Buster Gun Switchback are really amazing. Love the sounds added and the subtle rock particles. Really nice to see that added. No note here, just admiring the work.
- Regarding Megaman anim issues: There is something off about Megaman's leg/hip/COG position. I don't know where the nudge happened, but this error is causing the legs to max out their length and 'snap' to a fully straight position. It creates awkward jump poses too among other visual strangeness. Probably the most important note in this list is addressing what happened and fixing this one.
- Megaman's Victory anim (fist in the air/bicep flex) still not firing when opening chests.
- Megaman clips through the floor when going up the snake room elevator. 
- There are times I really like Megaman's hair and others where I can't stand it. The hair in the elevator looks ridiculous and should be fixed at some point. Either we need to override stiffness on the dynamic properties during certain triggerable actions, and allow it to flow at others, or it just needs to be replaced with something more traditional and better.
- Would like to add turning anims so megaman doesn't just slide rotate whenever the player turns in place.
- This may have to do with the shifted pose causing the leg stretch, but I'm still seeing significant noise/jittering in Megaman's standing pose, where his upper torse spazes out at certain points.
- Would be nice to see Megaman's lock-on smart select the closest target. Currently looks like it auto-selects the target megaman is looking towards, rather than the target closest to him. I think that's what's happening anyway. more often than not i'm wishing he selected the closer target instead of the one next to the closer target.
- It would be nice to have the refractor loot containers fracture and explode when they blow up, then the debris can slowly dither away after showing some physics. Also the boxes need physics enabled so they don't float around.
- Regarding Zakobon AI and updates. Really feel like the Zakobon has come into it's own and feels very good now. My only note and thing I think we should add at this point in time is that the Zakobon still doesnt detect Megaman when fired upon at a greater threshold from their perception distance. They should detect him at least when fired upon. If their perception still can't pick up megaman's position, then perhaps we should at least have them react and do their scan anim and use that detection noise. Something like that.
- Regarding Canam AI and updates. The Cannam fight is still very buggy and inconsistent. Uses the slap too often. Should probably have a rule that only lets him use it once and then jumps to the ceiling to get away. Still very buggy on the jumps and landings. Not sure how to fix this issue but we definitely need adjustments so he reacts more natural. Also looks like we need some anims to make him turn left or right.
- Regarding Mirumijee AI and updates. I would like to add the mirumijee snake lunge anim/attack. It just adds so much to the anxiety of fighting the snakes. They need to jump and lunge at Megaman. I'll try to get a Start, Air, End lunge attack anims for you as soon as I can. Imagine like 5 of those things jumping after megaman all at once. We need it.
------------------------ 
At least a few of those are must have fixes but a lot of them require some extra noodling and new anim assets. I figure lets cover the big ones first and move down this list. Let me know if you have any questions... Everything listed here is visible in my playthough. I recorded it and uploaded it to YT. See it here (unlisted)

https://youtu.be/QB3ZOy7k9Kg

Looking at this build I can't believe how far we've come. It's taken longer than I think we both would have liked probably but I am stunned at how good our project plays and it isn't even finished yet. Anyway, thanks for taking a look at these and let me know what you think.

Cheers!

2021-12-03 19:24 UTC, DamnedNForsaken commented
I'm putting a ticket up on the IK issues. I haven't had time to dig into yet but just like everything else probably have to just stick away at it.

Treasure chest, Siph has said that he has updated something on this, when we sync I'll make sure that it is up to spec

Noted on the elevator, pushing this to the right as that whole env will be updated, so this will be a next release thing.

Hell yeah on the turning animations for spinning in place. The original has this and it is something I always really wanted this in our game and would love this.

I'ma a little feed up with the lock on myself, needs more noodling.

The Zakoban, yep I know what you mean. I was debating for the longest on how to do this cleanly but I think the best approach now that I actually understand him more is to just flip the switch for wandering. As they may likely be already scanning or something. I could also do the sfx beep but I don't want to run into the double beep thing

Started updating the boxes. Fixes incoming.

Oh the spider... After a bunch of different poc, I'm back to square one on him. I think I understand him more now. This item still remains, same page.

I'm finally happy with the snakes, the logic is much cleaner now and does what is expected of it, (before they just chased and was broken).
Yep those lunges would be nice, and we are all aware more of root motion for the animations so when you get these updates in will definitely implement! :)

2021-12-03 23:18 UTC, DamnedNForsaken commented
^terrible commit message, and don't want to bother with a change.
But reaverbots now wander, if hit by bustershot

2021-12-06 22:39 UTC, DamnedNForsaken commented
Spider has now been updated. He's a SOB but working!

2021-12-08 08:29 UTC, JJChalupnik approved these changes
I think this is a great build. Also noticed a few very nice 'easter eggs' of sorts.... 

I'm gonna approve and merge so we get these in. Yay!!!

So first.... burnt birds when you shoot them... who did this? hahaha. Also, did Megaman's armor get darker after shooting them... Because I think we should do that as a throwback if it's not in there. Maybe after shooting 5 birds he goes dark megaman. People will eat it up big time. I love that you added the drips as well. All really great things.

AI for spider is much much better. Zakobon feels about perfect now imho. Here's some thoughts based on my latest playthrough that we can address now or coming up.

- Personally, I think if Megaman has a lock-on, he should always be able to fire his buster. So if the player is running away, then we should be able to have a use case where when they fire while running away, Megaman switches orientation to fire, much like he does when not locked on. This would basically function as it does when he normally faces an enemy, and would make the gameplay feel snappier. 
- Megaman still has jitters because of our look-at situation. If you aim up and to the side, and leave the angle there, Megaman will jitter a lot from the waist up. This is definitely something to fix and look into. I think it is because we are constantly checking to see if the player is looking, then auto-positioning him back to idle if the player doesn't input anything. I know we've had this issue forever but we definitely need to sort it out. Let's def chat about ways we might be able to approach this particular problem.
- Camera is locked when hanging on a surface. This is something we should definitely allow. Player should be able to rotate camera around while hanging from a ledge. Nice job fixing the anims though. they look much better this time around.
- The Refractor boxes feel so good now with the physics and destructability added. For the next pass on these, I'd like to hollow out the refractor boxes. That way they aren't solid masses when they blow up. (Although I kinda like it.) I might be sold on keeping them chunky like that and not hollowed out if we can add to the explosion when they are destroyed. Currently they sorta collapse which is nice but also missing some flair that would be nice to see. We should definitely expand on that.
- We should also remove the Emissive channel or override the emissive to black after the box is 'destroyed'. That way the flickering is gone and the box now feels like it is destroyed and no longer functioning.
- I think we should stiffen the hair physics by at least 25%, and really stiffen it up when Megaman goes up and down the elevator. If there's a set attribute function for these we can place on a timer or something I think that would help a lot in preventing Megaman from looking silly when he goes up and down the elevators. Who knows, maybe it will be good enough to where we can move on and not have a need to make a new set of rigged hairs.

The game is really feeling strong.

2021-12-08 08:29 UTC, merged